#!/bin/bash

NEW_IP=$2

echo "==== Obtaining new credentials for rejoining Kubernetes cluster ===="

kubeadm_token=$(kubeadm token create --ttl 4h --description "Token generated by LambdaStack for 'kubeadm join'.")

cert_hash=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //')

server_api_url="$NEW_IP:6443"

echo "Use following credentials for joining cluster. Execute following actions ONLY on worker Nodes."
echo "Modify file /etc/kubeadm/kubeadm-join.yml on each node with following values:"
echo "token: $kubeadm_token"
echo "cert hash: sha256:$cert_hash"
echo "server api url: $server_api_url"

echo "==== Obtaining credentials completed ===="
