@startuml LambdaStack System Context Diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

title LambdaStack System Context Diagram

Person(admin, "Admin", "Creates and manages LambdaStack environment.")
Person(developer, "Developer", "Uses LambdaStack components to provide middleware for hosted applications.")
Person_Ext(user, "End user", "Uses hosted applications to get business value.")

System(lambdastack, "LambdaStack Client", "Provides configuration, templating and management abstraction. ")
System(LambdaStack, "LambdaStack managed environment", "Provides integrated services for developers to run their applications.")
System(workload, "Application", "Provides business value.")

System_Ext(provider, "Infrastructure provider", "Provides infrastructure to run LambdaStack services and hosted applications.")

Rel(admin, lambdastack, "uses", "Console")
Rel(lambdastack, LambdaStack, "operates", "SSH/HTTPS")
Rel(developer, LambdaStack, "deploys applications to", "HTTPS")
Rel(developer, workload, "provides")
Rel(workload, LambdaStack, "executes on")
Rel(user, workload, "accesses", "TCP")

Rel(LambdaStack, provider, "executes on")
@enduml
