@startuml LambdaStack Component Diagram (human interactions)
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

title LambdaStack Component Diagram (human interactions)

LAYOUT_LEFT_RIGHT

Person(admin, "Admin", "Creates and manages LambdaStack environment.")
Person(developer, "Developer", "Uses LambdaStack components to provide middleware for hosted applications.")
Person_Ext(user, "End user", "Uses hosted applications to get business value.")


Container_Boundary(LambdaStack, "LambdaStack managed environment"){

    Container(orchestrator, "Containers Orchestrator", "kubernetes")
    Container(logging, "Logging", "EFK")
    Container(monitoring, "Monitoring", "Prometheus + Grafana")
    Container(streams, "Streams Processing", "Apache Kafka")
    Container(rdb, "Relational Database", "PostrgreSQL")
    Container(lb, "Load Balancer", "HAProxy")
    Container(messages, "Message Broker", "RabbitMQ")
    Container(memdb, "In-Memory Database", "Apache Ignite")
    Container(vault, "Vault", "Hashicorp Vault")
    Container(repository, "Repository", "Apache")
    Container(auth, "Authentication and Authorization", "Keycloak")

}

System(lambdastack, "LambdaStack Client", "Provides configuration, templating and management abstraction. ")
System(workload, "Application", "Provides business value.")

System_Ext(provider, "Infrastructure provider", "Provides infrastructure to run LambdaStack services and hosted applications.")

Rel(admin, lambdastack, "uses", "Console")

Rel(developer, orchestrator, "deploys applications to")
Rel(developer, streams, "manages")
Rel(developer, rdb, "manages")
Rel(developer, memdb, "manages")
Rel(developer, messages, "manages")
Rel(developer, auth, "manages")
Rel(developer, lb, "manages")
Rel(developer, vault, "manages")
Rel(developer, workload, "provides")

Rel(user, lb, "accesses", "TCP")
Rel(user, orchestrator, "accesses", "TCP")

Rel(lambdastack, provider, "operates")
Rel(lambdastack, orchestrator, "operates")
Rel(lambdastack, logging, "operates")
Rel(lambdastack, monitoring, "operates")
Rel(lambdastack, streams, "operates")
Rel(lambdastack, rdb, "operates")
Rel(lambdastack, lb, "operates")
Rel(lambdastack, vault, "operates")
Rel(lambdastack, repository, "operates")
Rel(lambdastack, memdb, "operates")
Rel(lambdastack, messages, "operates")
Rel(lambdastack, auth, "operates")

@enduml
